default_language_version:
    python: python3.12

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-toml
  - id: check-yaml
  - id: check-json
  - id: trailing-whitespace
  - id: end-of-file-fixer

- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 25.1.0
  hooks:
  - id: black

- repo: https://github.com/PyCQA/flake8
  rev: 7.3.0
  hooks:
  - id: flake8
    additional_dependencies:
      - pep8-naming
      - flake8-implicit-str-concat
      - flake8-pyproject
      - flake8-bugbear

- repo: https://github.com/PyCQA/isort
  rev: 6.0.1
  hooks:
    - id: isort

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.16.1
  hooks:
    - id: mypy
      args:
        - --non-interactive
        - --install-types
        - --no-strict-optional
      additional_dependencies:
        - types-mock
        - types-freezegun
        - pydantic
        - pydantic-settings
        - types-redis
        - types-pyyaml

- repo: https://github.com/asottile/pyupgrade
  rev: v3.20.0
  hooks:
  - id: pyupgrade
    args: [--py312-plus]

- repo: https://github.com/jazzband/pip-tools
  rev: 7.4.1
  hooks:
  - id: pip-compile
    name: pip-compile requirements.in
    files: ^(setup\.cfg|requirements\.in|requirements\.txt)$
    args:
    - "--emit-index-url"
    - "--output-file"
    - "requirements.txt"
    - "requirements.in"
